#ifndef WORLDDEFENDERS_ENTITYTYPE_H
#define WORLDDEFENDERS_ENTITYTYPE_H
enum EntityType {
	ETPLAYER,
	ETSHOOTER,
	ETCOLLISIONER,
	ETEBULLET,
	ETLASER
};
#endif // !WORLDDEFENDERS_ENTITYTYPE_H

